Evidex/Models/ClaimModel.cs
using System.ComponentModel.DataAnnotations;

namespace Evidex.Models
{
    public class ClaimModel : IndexItemModel
    {
        [Required]
        [StringLength(250, 
            ErrorMessage ="A claim should be 50-250 characters.", 
            MinimumLength = 50)]
        public string Claim { get; set; }
    }
}

Evidex/Models/ErrorViewModel.cs
namespace Evidex.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Evidex/Models/IndexItemModel.cs
using System.ComponentModel.DataAnnotations;

namespace Evidex.Models
{
    public class IndexItemModel
    {
        [Key]
        public Guid Id { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime CatalogedAt { get; set; }
    }
}

Evidex/Models/ProfileModel.cs
namespace Evidex.Models
{
    public class ProfileModel : IndexItemModel
    {
    }
}

Evidex/Models/UserModel.cs
using System.ComponentModel.DataAnnotations;

namespace Evidex.Models
{
    public class UserModel
    {
        [Key]
        public Guid UserId { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "User name must be of " +
            "positive length less than 100 charachters.",
            MinimumLength = 1)]
        [Display(Name = "User name:")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "First name must be of " +
            "positive length less than 100 charachters.",
            MinimumLength = 1)]
        [Display(Name = "Last name:")]
        public string LastName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Last name must be of " +
            "positive length less than 100 charachters.",
            MinimumLength = 1)]
        [Display(Name = "First name:")]
        public string FirstName { get; set; }

        [Display(Name = "Email address:")]
        public string? Email { get; set; }

        public Guid? ProfileID { get; }
    }
}

Evidex/Controllers/HomeController.cs
using Evidex.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Evidex.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index() { return View(); }

        public IActionResult Privacy() { return View(); }

        public IActionResult About() { return View(); }

        public IActionResult Search() { return View(); }

        public IActionResult Map() { return View(); }

        public IActionResult Statistics() { return View(); }

        public IActionResult Authors() { return View(); }

        public IActionResult Publishers() { return View(); }

        public IActionResult Profile() { return View(); }

        public IActionResult Logout() { return View(); }

        public IActionResult Explore() { return View(); }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Evidex/Controllers/UserModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Evidex.Data;
using Evidex.Models;

namespace Evidex.Controllers
{
    public class UserModelsController : Controller
    {
        private readonly EvidexContext _context;

        public UserModelsController(EvidexContext context)
        {
            _context = context;
        }

        // GET: UserModels
        public async Task<IActionResult> Index()
        {
              return _context.UserModel != null ? 
                          View(await _context.UserModel.ToListAsync()) :
                          Problem("Entity set 'EvidexContext.UserModel'  is null.");
        }

        // GET: UserModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // GET: UserModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,LastName,FirstName")] 
                                                UserModel userModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (userModel != null)
            {
                _context.UserModel.Add(userModel);
                await _context.SaveChangesAsync();
            }
           
            return RedirectToAction(nameof(Index));
            /*
            if (ModelState.IsValid)
            {
                _context.Add(userModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);*/
        }

        // GET: UserModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel.FindAsync(id);
            if (userModel == null)
            {
                return NotFound();
            }
            return View(userModel);
        }

        // POST: UserModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,SignedUpAt,Type")] UserModel userModel)
        {
            if (id != userModel.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserModelExists(userModel.UserName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: UserModels/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel
                .FirstOrDefaultAsync(m => m.UserName == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // POST: UserModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.UserModel == null)
            {
                return Problem("Entity set 'EvidexContext.UserModel'  is null.");
            }
            var userModel = await _context.UserModel.FindAsync(id);
            if (userModel != null)
            {
                _context.UserModel.Remove(userModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserModelExists(string id)
        {
          return (_context.UserModel?.Any(e => e.UserName == id)).GetValueOrDefault();
        }
    }
}

Evidex/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="text-center">
    <h1 class="display-4">What Evidex is all about:</h1>
</div>

Evidex/Views/Home/Authors.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Evidex/Views/Home/Explore.cshtml
@{
    ViewData["Title"] = "Explore";
}

<div class="text-center flex-grow-1 justify-content-evenly">
    <h1 class="display-4">Explore Our Catalog Of Claims</h1>
    <p>Browse our list of processed and reviewed claims</a>.</p>
</div>
<h4></h4>
<div class="text-center flex-grow-1 justify-content-evenly">
    <h1>Our Database Of Claims:</h1>
</div>

Evidex/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center flex-grow-1 justify-content-evenly">
    <h1 class="display-4">Welcome to Evidex!</h1>
    <p>A place where you can explore evidence for various claims</a>.</p>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1 justify-content-center justify-content-evenly">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Public User</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="UserModels" asp-action="Create">Create Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Explore">Explore Existing Claims</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Our Newsletter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Issue Claim</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Donate</a>
            </li>
        </ul>
    </div>
</div>

Evidex/Views/Home/IssueClaim.cshtml
@{
    ViewData["Title"] = "Explore";
}

<div class="text-center flex-grow-1 justify-content-evenly">
    <h1 class="display-4">Issue Claim</h1>
    <p>Don't see a claim you are inerested in? Issue a claim here:'</a>.</p>
</div>
<h4></h4>

Evidex/Views/Home/Map.cshtml
@{
    ViewData["Title"] = "Map";
}

<div class="text-center">Map:</h1>
    <p>Explore our interactive map of all cataloged claims</a>.</p>
</div>

Evidex/Views/Home/Publishers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Evidex/Views/Home/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<div class="text-center">
    <h1 class="display-4">Search:</h1>
    <p>See if we have an entry for a clim you're interested in, or creat a new claime</a>.</p>
</div>

Evidex/Views/Home/Statistics.cshtml
@{
    ViewData["Title"] = "Statitistics";
}

<div class="text-center">
    <h1 class="display-4">Statitistics:</h1>
    <p>Explore varous statistics concernening our database of claims</a>.</p>
</div>

Evidex/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Evidex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Evidex.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Evidex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center justify-content-evenly">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Search">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Map">Map</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Authors">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Publishers">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Profile</a>
                        </li>
                        <li class="nav-item" background-color="#0077cc">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Logout</a>
                        </li>
                    </ul>
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dark</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>     
    </menu>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Evidex - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Evidex/Views/UserModels/Create.cshtml
@model Evidex.Models.UserModel

@{
    ViewData["Title"] = "Create";
}

<h1>New user? Register here!</h1>
<h4>Please enter the following information:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <h4></h4>
            <h4></h4>
            <div class="form-group">
                <input type="submit" value="Create New User" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Evidex/Views/UserModels/Delete.cshtml
@model Evidex.Models.UserModel

@{
    ViewData["Title"] = "Delete";
}

Evidex/Views/UserModels/Details.cshtml
@model Evidex.Models.UserModel

@{
    ViewData["Title"] = "Details";
}

Evidex/Views/UserModels/Edit.cshtml
@model Evidex.Models.UserModel

@{
    ViewData["Title"] = "Edit";
}

Evidex/Views/UserModels/Index.cshtml
@model IEnumerable<Evidex.Models.UserModel>

@{
    ViewData["Title"] = "Index";
}

<h1>User Managment Page</h1>

<p>
    <a asp-action="Create">Create New User</a>
</p>